// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// import 'package:firebase_core/firebase_core.dart';

// ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHRGfCP_CuG80dnyfA2bJKKFsUQcAT0Ro',
    appId: '1:309770263458:web:cd58504d6117c0ac89f0fb',
    messagingSenderId: '309770263458',
    projectId: 'wintracker-6a8a3',
    authDomain: 'wintracker-6a8a3.firebaseapp.com',
    storageBucket: 'wintracker-6a8a3.firebasestorage.app',
    measurementId: 'G-3H3XNJPGYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHVWCsUokPOZMQz_WLjq5VO7we-ou3k4',
    appId: '1:309770263458:android:7440c237b2db126489f0fb',
    messagingSenderId: '309770263458',
    projectId: 'wintracker-6a8a3',
    storageBucket: 'wintracker-6a8a3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHRGfCP_CuG80dnyfA2bJKKFsUQcAT0Ro',
    appId: '1:309770263458:web:180e933a90ee069789f0fb',
    messagingSenderId: '309770263458',
    projectId: 'wintracker-6a8a3',
    authDomain: 'wintracker-6a8a3.firebaseapp.com',
    storageBucket: 'wintracker-6a8a3.firebasestorage.app',
    measurementId: 'G-FC98F6GNR0',
  );
}
